version: '3'

services:
  flask:
    build: . # Builds the Dockerfile in the same folder as the compose file.
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:5000:5000" # Set host to be 127.0.0.0 instad of 0.0.0.0. So that it can not be accessed directly remotly with: "IP_to_server:5000".
    command: gunicorn -w 1 -b :5000 run:app --reload # Remove --reload before deployment to production. The number '1' is the number of workers. Usually the same as the server CPU Core count.

  nginx:
    build: ./proxy # Builds the Dockerfile in the proxy folder.
    volumes:
      - ./app/static/:/etc/nginx/static # Since the app/static folder is one folder up, COPY in the Dockerfile does not work. 
                                        #Read more about the difference between volumemounting and copying. 
    ports:
      - "80:80" 
    depends_on:
      - flask
