version: '3'

services:
  flask:
    container_name: flask
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b :5000 run:app

  nginx:
    container_name: nginx
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - flask
